### ISSUE TITLE
The error for 2FA is returned with key "email"

### ISSUE THREAD

**Issue by mokhosh** [laravel/fortify#236]
- Fortify Version: 1.7.7

### Description:
When I input a wrong 2FA code and get redirected back to the login page, the error message is returned under the key "email" which doesn't make any sense.

I have set `fortify.username` config to `login` and it makes more sense to at least use the `username` set in the config, if we are gonna send it under anything other than `two-factor-authentication-code`.

### Steps To Reproduce:
- input wrong 2FA code on challenge page
- `dd` the `$errors` on login page

**Comment by driesvints** [comment]
Indeed. That seems odd to me as well. I'll check with @taylorotwell.

**Comment by driesvints** [comment]
So we won't be able to change this atm because it'd break all Jetstream apps. The earliest we can change this is in the next Fortify version. You're free to send a PR to master if you like. We'll also need to update Jetstream's master branch in that case and bump the minimum version of Fortify to `^2.0` for its composer dependencies.
