### ISSUE TITLE
2FA after PasswordConfirmView only works on second submit

### ISSUE THREAD

**Issue by walerii** [laravel/fortify#263]
- Fortify Version: ^1.7
- Laravel Version: 8
- PHP Version: ^7.3|^8.0

### Description:

I have an issue regarding the PasswordConfirm Fortify function. When enabling 2FA the password-confirm view appears correct, but after submitting the password, the 2FA is still disabled and I won't get the status for 2FA. Only on the second submit, after the password has been confirmed, the 2FA is activated. The same behavior goes for the deactivation of the 2FA-functionality.

**Comment by driesvints** [comment]
Heya, thanks for reporting.

I'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new fortify-issue-263 --github="--public"
```

After you've posted the repository, I'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by daniesy** [comment]
This issue is still reproducible in the latest release. It should be opened.

**Comment by nb823** [comment]
The official docs for Fortify's password confirmation say:
"If the password matches the user's current password, Fortify will redirect the user to the route they were attempting to access."
Since that is still not true for POST requests, this issue should be considered a bug and be re-opened.
https://laravel.com/docs/10.x/fortify#password-confirmation

**Comment by lucadegasperi** [comment]
I can confirm this issue needs to be reopened as POST requests are not actually replayed after the password confirmation screen.

**Comment by bessone** [comment]
I confirm the behavior.

With the password protection of the store and destroy of the two factor, after the confirmation the POST or DELETE are not executed but the GET returning to the previous page.
