### ISSUE TITLE
Throttle middleware does not play nicely with Inertia

### ISSUE THREAD

**Issue by bastinald** [laravel/fortify#312]
I'm trying to use Fortify with Inertia and everything works great except the throttle middleware is not returning a status or error which I can use inside my Vue components. 

Instead, I get this: https://i.imgur.com/yWpXMVp.png

Am I missing something? How can I get the throttle middleware that Fortify uses to give me a `status` or `errors` which I can use in my Vue components? I'd need this for login, verify email, etc.

**Comment by bastinald** [comment]
submitted PR so we can set our own limiter response like we can with `login`: https://github.com/laravel/fortify/pull/313

**Comment by brnquester** [comment]
@bastinald - I understand this issue is old, but the Lockout Fortify own handler that plays nicely with InertiaJS is still present but never reached due to the Laravel middleware. However, with simple steps, I was able to get it working back again. This to me seems like an existing bug. The Laravel middleware should be an option that we enable or not, but never the only option. Any support in my current issue is appreciated.
https://github.com/laravel/fortify/issues/543
