### ISSUE TITLE
authenticateThrough doesn't work as expected with 2FA

### ISSUE THREAD

**Issue by mojowill** [laravel/fortify#390]
- Fortify Version: 1.13.0
- Laravel Version: 9.13.0
- PHP Version: 8.1.6
- Database Driver & Version: MySQL 8

### Description:
When using `Foritfy::authenticateThrough()` with 2FA enabled additional steps in the pipeline are not executed. I followed the docs to add the default pipeline hoping to add some additional logic once the user was logged in. This works as expected for a user without 2FA but when a user has 2FA enabled they don't seem to go back to the pipeline after `RedirectIfTwoFactorAuthenticable`

### Steps To Reproduce:

Code in my `FortifyServiceProvider.php`

```php
Fortify::authenticateThrough(static function (Request $request) {
            return array_filter([
                config('fortify.limiters.login') ? null :
                    EnsureLoginIsNotThrottled::class,
                Features::enabled(Features::twoFactorAuthentication()) ? RedirectIfTwoFactorAuthenticatable::class : null,
                // Nothing from here gets called if the user has 2FA enabled
                AttemptToAuthenticate::class,
                PrepareAuthenticatedSession::class,
                MyCustomClassWhichNeverGetsCalledOn2FA::class,
            ]);
        });
```

I expected the user to authenticate and then the pipeline steps to be followed?

**Comment by driesvints** [comment]
Heya, thanks for reporting.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue as separate commits on the main/master branch and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by afifosh** [comment]
@driesvints  the repo its not required .. if a user enable the 2fa so basically he will stack on this "RedirectIfTwoFactorAuthenticatable::class" and after successfully adding the correct code from Google Authenticator the remaining class will be ignored and not executed 
                AttemptToAuthenticate::class,
                PrepareAuthenticatedSession::class,
                MyCustomClassWhichNeverGetsCalledOn2FA::class,

inside the RedirectIfTwoFactorAuthenticatable::class referring to store in the controller the user will be automatically logged in and he will be redirected to the Home page..

**Comment by thebillharris** [comment]
In my opinion This should never have been closed.  I have had the same experience. If Fortify 2fa is enabled,  nothing below `Features::enabled(Features::twoFactorAuthentication()) ? RedirectIfTwoFactorAuthenticatable::class : null,` executes.

**Comment by thebillharris** [comment]
My repository is private, but this is easily reproducible. Add a log directive inside the closure:

`Fortify::authenticateThrough(function (Request $request) {
    return array_filter([
            config('fortify.limiters.login') ? null : EnsureLoginIsNotThrottled::class,
            Features::enabled(Features::twoFactorAuthentication()) ? RedirectIfTwoFactorAuthenticatable::class : null,
            //AttemptToAuthenticate::class,
            //PrepareAuthenticatedSession::class,
            Log::info('You aren't here');
    ]);
});`

The Log directive will not execute.

**Comment by afifosh** [comment]
If a user logs in through 2FA, the remaining class will not be executed. To address this, Implement an event listener that responds to user login events in Laravel. This event listener will be triggered whenever a user successfully logs in, allowing you to perform specific actions or execute other classes as needed.

**Comment by mojowill** [comment]
> If a user logs in through 2FA, the remaining class will not be executed. To address this, Implement an event listener that responds to user login events in Laravel. This event listener will be triggered whenever a user successfully logs in, allowing you to perform specific actions or execute other classes as needed.

I don't think anyone is disputing that are ways around this, but there are just that. Ways around the framework not behaving as documented.

**Comment by stevethomas** [comment]
Just encountered this; yes it is a bit unexpected. 

Workarounds include:
- listening for`Illuminate\Auth\Events\Login`
- implementing `TwoFactorLoginResponse` and calling the last bits of the pipeline there

It makes sense why the pipeline is temporarily halted due to the redirect, but I think it would make sense for `TwoFactorAuthenticatedSessionController` to complete the rest of the pipeline after verification.

Another gotcha is that the rate limiter is not cleared in the 2FA flow because `PrepareAuthenticatedSession` is never called.
