### ISSUE TITLE
provide a way to overwrite logout method

### ISSUE THREAD

**Issue by ChaudharyHabib** [laravel/fortify#405]
I don't want to destroy all session data upon logout. How to overwrite that method?\Laravel\Fortify\Http\Controllers\AuthenticatedSessionController@destroy

what I'm doing now is 

```
use App\Http\Controllers\Controller;
use Laravel\Fortify\Http\Controllers\AuthenticatedSessionController;
use Illuminate\Http\Request;
use Laravel\Fortify\Contracts\LogoutResponse;
class LogoutController extends AuthenticatedSessionController
{

    /**
     * Destroy an authenticated session.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Laravel\Fortify\Contracts\LogoutResponse
     */
    public function destroy(Request $request): LogoutResponse
    {
        $this->guard->logout();

        $request->session()->invalidate();

        $request->session()->regenerateToken();

        return app(LogoutResponse::class);
    }
    
}
```

above is able to work but for this, I have to register a new route. But I wanted to use /logout but it's under use by fortify
I also checked that I couldn't disable the logout feature in fortify like how I can do for register

**Comment by driesvints** [comment]
Seems like you found a way to make this work so not sure what the feature request is here.

**Comment by Aidi225** [comment]
@driesvints  I encountered a similar problem.
I have two sessions named 'res' and 'pre', which are set based on request parameters. These sessions should remain valid regardless of whether the user logs in, logs out, or navigates to a different page. They should only expire when the browser is closed. But right now, when a user logs out, these two sessions disappear.

I made a post on Laracasts.  -> [How can you prevent Laravel Fortify's Logout from destroying all sessions?](https://laracasts.com/discuss/channels/laravel/how-can-you-prevent-laravel-fortifys-logout-from-destroying-all-sessions)

@oldravian  

Do you have a more viable solution? Although I'm not familiar with the method of overriding routes, I can grasp what you're conveying, and such a solution feels unsatisfactory. This issue is vital for our development. If you have any constructive suggestions or know the method for overriding, I'm willing to compensate you for your insights on the paid Q&A platform, [KeyPulse](https://keypulse.xyz).
