### ISSUE TITLE
Verify email without logging in

### ISSUE THREAD

**Issue by nmalcolm** [laravel/fortify#444]
Currently, the email verification link requires users to login first. As an end user, if I've just signed up on my computer and I try to verify from my phone (a common scenario), I'm forced to login and some people may abandon at this point. If they don't, they'll at the very least be frustrated they need to do this. I know I am when this happens.

There's a few other people asking how to do this, and a StackOverflow question about it has an accepted answer in which the author admits it doesn't even verify the hash at all...

https://stackoverflow.com/questions/64172138/laravel-8-how-do-i-verify-the-users-email-address-after-registration-without-ha

**Comment by driesvints** [comment]
Thank you for this request. We've had this one in the past for sure. Right now we're not planning on making any changes to this, sorry. You can always try to attempt a new PR to see if it'll get accepted.

**Comment by dwightwatson** [comment]
I've run into this issue because I have users who register through an app (using an API) and then are forced to login to the website in order to verify their email, which is a little cumbersome. I do think it would be nice for Fortify to better support this use case, perhaps even just for a hook in to customise the middleware on this route.

I've updated the answer on that Stack Overflow question to include the authorization handling that normally takes place in `VerifyEmailRequest`).

**Comment by nmalcolm** [comment]
I finally came back to this and managed to get something working using the code from StackOverflow, plus a couple of additions.

```
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Auth\Events\Verified;
use Illuminate\Http\Request;
use Laravel\Fortify\Contracts\VerifyEmailResponse;
use Illuminate\Support\Facades\Auth;

class VerifyEmailController extends Controller
{
    public function __invoke(Request $request)
    {
        $user = User::findOrFail($request->route('id'));

        if (! hash_equals(sha1($user->getEmailForVerification()), (string) $request->route('hash'))) {
            throw new AuthorizationException();
        }

        if ($user->hasVerifiedEmail()) {
            Auth::loginUsingId($user->id, $remember = true);
            return app(VerifyEmailResponse::class);
        }

        if ($user->markEmailAsVerified()) {
            Auth::loginUsingId($user->id, $remember = true);
            event(new Verified($user));
        }

        return app(VerifyEmailResponse::class);
    }
}
```

It's probably not the best way but it solves the problem.

**Comment by projct1** [comment]
Same problem, I'm exhausted and don't understand how to solve it. Users register, then follow the link in the email to confirm their email and can open it in a different browser than the one they registered in and are already authorized in. And Laravel redirects to the login page instead of just confirming the email. The middleware `Illuminate\Auth\Middleware\Authenticate` is triggered, which redirects to the login page, since I am supposedly not authorized.
I have all the default settings for auth and fortify.

**Comment by projct1** [comment]
I solved it by added this code to `FortifyServiceProvider`:
```php
Authenticate::redirectUsing(function(Request $request) {
    if ($request->routeIs('verification.verify')) {
        Auth::loginUsingId($request->route('id'));

        return route('verification.verify', [
            'id' => $request->route('id'),
            'hash' => $request->route('hash'),
            'expires' => $request->query('expires'),
            'signature' => $request->query('signature')
        ]);
    }
});
```
