### ISSUE TITLE
Fortify Routes

### ISSUE THREAD

**Issue by undjike** [laravel/fortify#96]
I'm facing a problem with **Fortify Routes** knowing that they are not exposed on **Auth::routes()** like **Laravel UI**. I want to populate Fortify Routes in a route group to enable route globalization. For instance...

```php
Route::localized(function () {
     // Fortify Routes here
});
```

**Comment by Okipa** [comment]
@undjike it seems that you'll currently have to call `Fortify::ignoreRoutes();` in the `register` method of the `FortifyServiceProvider`.

Then, copy and paste the routes declared in the `/vendor/laravel/fortify/routes/routes.php` file into your route group (I suppose that you'll also have to execute a translation method on the URI param of the route in order to have it translated).

This is how I managed to do so after exploring this package.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
